# Generated by Django 5.0.1 on 2025-02-01 18:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("llm_providers", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="System prompt that defines the agent's role and behavior"
                    ),
                ),
                (
                    "user_prompt_template",
                    models.TextField(help_text="Template for formatting user requests"),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="Controls randomness in the model's output",
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum tokens for response. If null, uses model's default",
                        null=True,
                    ),
                ),
                (
                    "stop_sequences",
                    models.JSONField(
                        default=list,
                        help_text="Sequences that will stop the model's generation",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Weight for this agent's vote in the final decision",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "llm_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agents",
                        to="llm_providers.llmmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.UUIDField()),
                ("request_data", models.JSONField()),
                ("response_data", models.JSONField(null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["is_active"], name="agents_agen_is_acti_e9c14d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["session_id"], name="agents_agen_session_532f8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["started_at"], name="agents_agen_started_f35943_idx"
            ),
        ),
    ]
