# Generated by Django 5.0.1 on 2025-02-01 18:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("api_key", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM Provider",
                "verbose_name_plural": "LLM Providers",
                "ordering": ["-priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider_type"], name="llm_provide_provide_858a60_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="llm_provide_is_acti_f2c616_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LLMModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("model_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("features", models.JSONField(default=dict)),
                ("max_tokens", models.IntegerField(default=4096)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="llm_providers.llmprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Model",
                "verbose_name_plural": "LLM Models",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="llm_provide_is_acti_113440_idx"
                    ),
                    models.Index(
                        fields=["model_name"], name="llm_provide_model_n_270534_idx"
                    ),
                ],
                "unique_together": {("provider", "model_name")},
            },
        ),
    ]
